# Generated by Django 3.2.7 on 2021-11-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nulo', max_length=30)),
                ('direccion', models.CharField(default='nulo', max_length=50)),
                ('correo', models.EmailField(default='nulo', max_length=30, unique=True)),
                ('telefono', models.CharField(default='nulo', max_length=10)),
                ('password', models.CharField(default='nulo', max_length=15)),
            ],
        ),
    ]
